### ISSUE TITLE
Cannot Start the Bot

### ISSUE THREAD

**Issue by MoTastisch** [botlabs-gg/yagpdb#1155]
I wanted to install this bot on my server. I followed this guide: https://hostyagpdb.xyz/selfhost/selfhostyag/
now i get this error when i try to run the bot:

INFO Starting YAGPDB version v1.31.20             
INFO Set redis pool size to 10                     p=common stck="common.connectRedis:common.go:232"
INFO max ccr set to: 25                            p=common stck="common.connectRedis:common.go:232"
INFO Set max PG connections to 3                   p=common stck="common.connectRedis:common.go:232"
INFO Retrieving bot info....                       p=common stck="common.connectRedis:common.go:232"
panic: &discordgo.RESTError{Request:(*http.Request)(0xc0003a5d00), Response:(*http.Response)(0xc00027e000), ResponseBody:[]uint8{0x7b, 0x22, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x3a, 0x20, 0x22, 0x34, 0x30, 0x31, 0x3a, 0x20, 0x55, 0x6e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x22, 0x2c, 0x20, 0x22, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x3a, 0x20, 0x30, 0x7d}, Message:(*discordgo.APIErrorMessage)(0xc00051e060)}

goroutine 1 [running]:
github.com/botlabs-gg/yagpdb/common.Init(0x0, 0x0)
        /home/motastish/yagpdb/common/common.go:108 +0x71f
github.com/botlabs-gg/yagpdb/common/run.Init()
        /home/motastish/yagpdb/common/run/run.go:112 +0x29f
main.main()
        /home/motastish/yagpdb/cmd/yagpdb/main.go:52 +0x26

sorry for my bad english :)

**Comment by ashishjh-bst** [comment]
Please ask questions related to self hosting in our support server, there is a channel for self hosters. 

Closing the issue.

**Comment by MoTastisch** [comment]
okay thanks anyways
