### ISSUE TITLE
password authentication failed for user "yagpdb"

### ISSUE THREAD

**Issue by Jack1424** [botlabs-gg/yagpdb#1329]
I'm trying to run YAGPDB using Docker on my server. I have ensured that the passwords in `app.env` and `db.env` match, but I still get this error when running `docker-compose -f docker-compose.yml up`.

Here is the full error:
```
app_1    | level=info msg="Starting YAGPDB version v2.6.2 release(abb8b0d)"
app_1    | level=info p=common msg="Set redis pool size to 10" stck="common.connectRedis:common.go:232"
app_1    | level=info p=common msg="max ccr set to: 25" stck="common.connectRedis:common.go:232"
db_1     | 2022-08-25 17:59:15.039 UTC [38] FATAL:  password authentication failed for user "yagpdb"
db_1     | 2022-08-25 17:59:15.039 UTC [38] DETAIL:  Password does not match for user "yagpdb".
db_1     |      Connection matched pg_hba.conf line 95: "host all all all md5"
app_1    | panic: pq: password authentication failed for user "yagpdb"
app_1    | 
app_1    | goroutine 1 [running]:
app_1    | github.com/botlabs-gg/yagpdb/v2/common.Init()
app_1    |      /home/vsts/work/1/s/gopath/src/github.com/botlabs-gg/yagpdb/common/common.go:102 +0x505
app_1    | github.com/botlabs-gg/yagpdb/v2/common/run.Init()
app_1    |      /home/vsts/work/1/s/gopath/src/github.com/botlabs-gg/yagpdb/common/run/run.go:112 +0x2fb
app_1    | main.main()
app_1    |      /home/vsts/work/1/s/gopath/src/github.com/botlabs-gg/yagpdb/cmd/yagpdb/main.go:52 +0x1d
yagpdb_docker_app_1 exited with code 2
```

I'm following the instructions at https://hostyagpdb.xyz/selfhost/docker/. Maybe something is broken or I (hopefully) just made a stupid mistake.

**Comment by ashishjh-bst** [comment]
As per the ReadMe, we only talk about issues in our support server.  

And this looks more like a config issue and not an actual bug, please continue the conversation in the support server. 
Closing this and locking the conversation.
